# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creditmanage', '0002_auto_20170217_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(default=b'2000-12-31')),
                ('expiry_date', models.DateField(default=b'2001-12-30')),
                ('isActive', models.IntegerField(default=1)),
                ('creditLine', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditmanage.creditCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
