# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanage', '0003_user_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_card',
            name='name',
            field=models.CharField(default=b'default', max_length=100),
        ),
    ]
