# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanage', '0004_user_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='isKeepable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='activation_date',
            field=models.DateField(default=b'2017-2-20'),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='expiry_date',
            field=models.DateField(default=b'2018-2-20'),
        ),
    ]
